# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Matr will create an R saprse matrix resized to the correct number of entries, but not filled
#' @aliases Matr,Dense2SparseHDF5-method
#' @rdname Matr
#' @description count the not zeros in a dense matrix
#' @param nrow row count
#' @param ncol col count
#' @param size the amount of not zero entries 
#' @return the propper resized dense matrix (hopefully)
#' @export
Matr <- function(nrow, ncol, size) {
    .Call('_Dense2SparseHDF5_Matr', PACKAGE = 'Dense2SparseHDF5', nrow, ncol, size)
}

#' @title NotNull returns the amount of not zwero entries in the matrix/vector
#' @aliases NotNull,Dense2SparseHDF5-method
#' @rdname NotNull
#' @description count the not zeros in a dense matrix
#' @param X a dense vector
#' @return the amount of not zero entries
#' @export
NotNull <- function(X) {
    .Call('_Dense2SparseHDF5_NotNull', PACKAGE = 'Dense2SparseHDF5', X)
}

#' @title add runs wilcox test on the columns of the sparse matrix
#' @aliases add,Dense2SparseHDF5-method
#' @rdname add
#' @description count the not zeros in a dense matrix
#' @param X the sparse matrix 
#' @param dat the dense matrix
#' @param alloc the amount of data that has to fit into the return object
#' @oaram proigressBar show a progress bar (default true)
#' @return null
#' @export
add <- function(X, dat, offset, alloc, progressBar = TRUE) {
    .Call('_Dense2SparseHDF5_add', PACKAGE = 'Dense2SparseHDF5', X, dat, offset, alloc, progressBar)
}

#' @title addVector runs wilcox test on the columns of the sparse matrix
#' @aliases addVector,Dense2SparseHDF5-method
#' @rdname addVector
#' @description count the not zeros in a dense matrix
#' @param dat the dense matrix
#' @param alloc the amount of data that has to fit into the object
#' @return null
#' @export
addVector <- function(dat, offset, alloc, progressBar = TRUE) {
    .Call('_Dense2SparseHDF5_addVector', PACKAGE = 'Dense2SparseHDF5', dat, offset, alloc, progressBar)
}

